#!/bin/sh

chosen="$(ls ~/cashew/gifs -1 | rev | cut -b 5- | rev | rofi -dmenu -matching normal -show-icons -i -p 'GIFs')"
chosen=$(echo $chosen | sed "s/\/home\/cashew\/\/gifs\///" | sed "s/\.gif//")

[ -z "$chosen" ] && exit
printf "https://gitlab.com/thecashewtrader/gifs/-/raw/main/$chosen.gif" | xclip -selection clipboard
xdotool key ctrl+v
sleep 0.15
xdotool key Return
