#!/usr/bin/bash
cd secretnotes
NOW=$(date +"%m-%d-%Y")
FILE="secret.$NOW.txt"
nvim $FILE
gpg -c --no-symkey-cache --cipher-algo AES256 $FILE
rm $FILE

# To decrypt the file run this
# gpg <your file name>
