#!/usr/bin/python

import os
from subprocess import call

pwd = os.getcwd()
names = os.listdir(pwd)
if '.git' in names:
    names.remove('.git')

for name in names:
    name = os.path.join(pwd, name)
    call(f'convert {name} -resize 48x0^ {name}', shell=True) 
